### ISSUE TITLE
Rewinding and Fast Forwarding are kind of broken with Hudson's sound driver.

### ISSUE THREAD

**Issue by BlinxTheWinx** [dgrfactory/spcplay#36]
Games: http://gdri.smspower.org/wiki/index.php/Super_Famicom/Super_NES_Sound_Driver_List#SFX_SOUND_DRIVER_.28Hudson.29
The player either doesn't skip or skips more than 5 seconds.

**Comment by dgrfactory** [comment]
Hi, @BlinxTheWinx
Thank you for reporting the issue.

~I tested with "Shin Momotarou Densetsu", "Super Bomberman 2", and "Super Bomberman 5" songs and it worked.
Could you please reply specifically about which game and track it occurred in?~

I was able to reproduce this problem.
This problem occurs because fast seeks do not emulate the DSP.
Please edit spcplay.ini as follows, fast seek is disabled:
```
SEEKFAST 1 : 1
    ⬇️
SEEKFAST 1 : 0
```
As a side effect, keep in mind that seek processing is slow.

**Comment by dgrfactory** [comment]
Recent personal computers have become high-performance.
Therefore, the seek is fast enough without using fast seek.

I will change the fast seek default to OFF in the next version.
That would be more beneficial for many users, at this time.

Thanks!

**Comment by dgrfactory** [comment]
https://github.com/dgrfactory/spcplay/releases/tag/2.19.0.7489
