### ISSUE TITLE
Failure to emulate echo buffer volume-related overflow effect from FIR coefficeints

### ISSUE THREAD

**Issue by KungFuFurby** [dgrfactory/spcplay#37]
Once again, I am merely forwarding a playback difference report from the Discord servers that I am in, since I myself don't use the player because of a platform incompatibility.

This is related to #23, except instead of a playback failure, it is a failure to emulate an overflow effect (by wraparound, instead of clamping) in the echo buffer related to the FIR coefficients. An example SPC file straight out of Super Famicompo 3 has been attached, since the difference in question occurs immediately at the beginning.

[Here is the SPC file in question in a .zip file.](https://github.com/dgrfactory/spcplay/files/7435964/SFC3Cover29.SPC.zip)

I actually gave it a quick go on my SD2SNES Pro/FXPak Pro cartridge on a 2/1/3 North American SNES/SFC unit and confirmed the bug in question. Feel free to double check the playback on your own SPU (SHVC-SOUND unit).

**Comment by dgrfactory** [comment]
Hi, @KungFuFurby
Thank you for reporting the issue.

I was able to confirm the difference from the actual machine (SHVC-SOUND).

The SNES SPC700 Player internally processing DSP at 32 bit-float for better sound quality, however the SHVC at 16 bit-int.
Therefore, if a loud echo feedback is output, SPC700 Player outputs sound as it is, but the SHVC will crack noise because overflow occurs.

I am currently investigating whether it can perform the same behavior as the SHVC.

**Comment by dgrfactory** [comment]
I found this cause and fixed implementation, currently testing now.
A fixed version will be released soon.
Please wait a little longer.

**Comment by dgrfactory** [comment]
Fixed in the following release:
https://github.com/dgrfactory/spcplay/releases/tag/2.19.0.7521

Note:
This fix has been found to reduce sound quality in just a few games. (I know this is right processing, but I like higher quality sound.)
Therefore, the flag must be ON for change the FIR filter behavior to the same as the actual device.

When "SNES Echo/FIR Method" flag in "Expansion Flags" settings is ON, the FIR filter is calculated in the same 16-bit as the actual device.
When OFF, calculated in 17-bit for higher sound quality.
