### ISSUE TITLE
Request: New debug information layout

### ISSUE THREAD

**Issue by livvy94** [dgrfactory/spcplay#42]
Hello! I compose SNES music with AddMusicK and the EarthBound Music Editor, and I'd love there to be a new debug view, or possibly a seperate window launched from one of the menus, that looks like this:

```
S#  ADSR/GAIN TUNING
00: FF F0 B8  0380
01: FF E0 B8  0300
02: FF F2 B8  0260
(information for the rest of the loaded samples goes here)

== DELAY PARAMETERS ==
CHANNELS: 3F | VOLUME: 2A 2A
DELAY: 03 | FEEDBACK: 20
FIR FILTER: 34 33 00 D9 E5 01 FC E6
```
To construct an instrument table in AddMusicK and EBMusEd, you need the ADSR and tuning data in this format - this kind of hexadecimal layout would make recreating this data in new musical arrangements much easier. Is something like this feasible in a future release?

**Comment by dgrfactory** [comment]
Hi, @vince94 
Thank you for reporting the new request.

I have never used AddMusicK, so I am not sure if it is working correctly, but I implemented it as a trial.
https://github.com/dgrfactory/spcplay/releases/tag/2.19.2.7663

### To display `S#  ADSR/GAIN TUNING`

1. Click "Settings" -> "Information Viewer" -> "Channel 2".
2. Push F12 or Pause/Break key.
3. Play music.

Note: However, I do not know if TUNING should indicate what exactly.
Now it displays the same value as PITCH.

### To display `DELAY PARAMETERS`

Originally, I think I can display the information you originally desired.
Click "Settings" -> "Information Viewer" -> "DSP"

**Comment by livvy94** [comment]
Wow, that was fast!
I like that Tuning is displaying the same thing as Pitch, but here's what I had in mind. In most Nintendo-developed games (using the Kankichi-kun sound driver), the Tuning value is what usually defines what the base pitch/Middle C of an instrument should be. Here's some [documentation](https://github.com/vince94/EarthBound-Instrument-Packer/blob/master/Documentation.md#spc-transfer-block---instrument-configuration-table) I wrote, and here's an example from a song in EarthBound:

![image](https://user-images.githubusercontent.com/12562322/160705025-bb26cb25-774c-4661-93d6-8b2f645e9051.png)

In a hex editor, this data looks like this: 
![image](https://user-images.githubusercontent.com/12562322/160705118-1f5db990-60ad-4fcd-ae35-9b4114e15898.png)

This isn't how every sound driver defines instruments, though, so I imagine implementing this wouldn't be as simple as I might think.

**Comment by dgrfactory** [comment]
Hi, @vince94

Thank you for replying with a detailed case study.
As a test, I added an algorithm to search the TUNING parameter from the APU RAM and changed it to display.

Please try the new release version.
https://github.com/dgrfactory/spcplay/releases/tag/2.19.2.7664
The operating procedure is the same as in the previous version.
(Click "Settings" -> "Information Viewer" -> "Channel 2", and push F12 key.)

Note:
It takes a little time until TUNING is displayed because it searches for parameters from RAM.
Also, since multiple waveforms are used for search, may not be displayed while simple sounds such as sound effects are being played.

**Comment by livvy94** [comment]
It seems to be working as expected! Thank you!
![image](https://user-images.githubusercontent.com/12562322/160908336-03a35783-d098-4e01-baca-db9be02dc941.png)

**Comment by KungFuFurby** [comment]
You'd be surprised what that can work on as far as exact retrieval... in theory. You should try it on games that use either David Whittaker's sound driver or the H-Sound Engine, which are otherwise not N-SPC. The instrument format is N-SPC compatible minus noise support.

I documented them here:
https://sneslab.net/wiki/David_Whittaker_Sound_Engine
https://sneslab.net/wiki/H-Sound_Engine

On the opposite end of the spectrum, though, you need to be prepared for more extreme circumstances when trying to calibrate ADSR and GAIN parameters (tuning may also vary). I explicitly cite Sculptured Software games, because they have a special system that adjusts the GAIN volume envelope on probably a per-tick basis. Software Creations and KaZe are another set, because they use direct GAIN for volume envelopes (I can say the same thing for SNESMod, but that's not a commercial era sound driver, having debuted in 2009).

**Comment by dgrfactory** [comment]
The following patterns are supported -- just a little, in this released version (build 7664).

* `aa bb cc [dd/??] ee ff`
* `[aa] bb cc dd ee ff`

```
aa ... Source Number
bb ... ADSR1
cc ... ADSR2
dd ... GAIN
ee ... BASE PITCH
ff ... BASE PITCH (fractional)
```

It is impossible to support all patterns, but if there is a pattern in high demand, I am likely to support.
For now, I will give this issue a "fixed" label.

**Comment by KungFuFurby** [comment]
I'll agree with this because I think it's essentially the most common instrument type as a direct result of being based off of what is effectively the most common music player (yes, music player: the SFX programming can be wildly different from game to game, and even the music player itself can also get modified, though usually the instrument format is not affected at all).

The second-to-most common sound driver I know of is Opus' SQ (usually with something called DBOOT, but that's SNES-side code, not SPC-side code). Its instrument format is not N-SPC/Kankichi, and it's quite a bit more complicated, at 16 bytes per entry, (likely) partially because it has dynamic channel allocation to sort out. I haven't fully reverse engineered the instrument format yet, and I don't think this is necessary at this time for SPCPlay. On a side note, its music format is actually compressed with some sort of LZ-esque format that it decompresses on the SPC700 side into a buffer.
