### ISSUE TITLE
Possible Echo/DSP bug or inacuraccy?

### ISSUE THREAD

**Issue by Pinci19** [dgrfactory/spcplay#52]
Hello, this is something I noticed a long time ago: I have a SPC that constantly updates the FIR Filter along some other echo parameters, and at one point, the echo in the kick drum channel is disabled so that it isn't affected by the FIR Filter any further, however, bsnes and many other emulators and players still output the first kick note with echo even after I disabled it, whereas SPCplay does not. I was wondering if it could be some kind of inaccurate emulation regarding SPCplay?
I have attached two audio files (including two extra ones with the kick isolated) and the original SPC file, the event occurs at 0:08.
[spcplay echo.zip](https://github.com/dgrfactory/spcplay/files/9465860/spcplay.echo.zip)

**Comment by dgrfactory** [comment]
Hi, @Pinci19 
Thank you for reporting the issue.

I played the attached SPC on the actual device (SHVC-SOUND), only the first key-on of drum (ch.7) at 00:08 was echoed, as you indicated.
Therefore, this appears to be a bug in SNESAPU.

Interestingly, when the playing speed was set to 110%, a drum was echoed.
Perhaps, it is due to a very slight difference in processing timing.

**Comment by dgrfactory** [comment]
Hi, @Pinci19
I have identified some memory handling bugs in echo processing,  and released a fixed version.
https://github.com/dgrfactory/spcplay/releases/tag/2.19.4.7818

Note, if the playing speed is changed to anything other than 100%, the echo may not be applied, as it will not behave the same as on the actual device.
This is because changing the playing speed intentionally changes the SPC700 clock, but maintains the DSP clock.

**Comment by Pinci19** [comment]
Awesome! Thank you!
