### ISSUE TITLE
Feature request - Piano roll viewer

### ISSUE THREAD

**Issue by GhbSmwc** [dgrfactory/spcplay#55]
I was thinking of this visualizer to be added:
![image](https://user-images.githubusercontent.com/13095760/200187997-cbd13186-b8ae-4677-bcc9-68a52ec6a235.png)
While the music may be a tracker format and does not know the notes in advance like a midi file, it at least knows the notes currently being played. This is why notes that have been played are displayed as a "rain" (named after miditrail) only to be displayed under the piano keys.
Source: https://www.youtube.com/watch?v=igP51SMfCYA

**Comment by dgrfactory** [comment]
Hi, @GhbSmwc
Thank you for reporting the new request.

The SNES SPC700 Player pursues a **"simple and compact design"** as described in [the "Features" section of the Wiki page](https://github.com/dgrfactory/spcplay/wiki#features).
Therefore, there are no plans to support flashy visualizers in the future.

There are already some SPC players that can display keyboard, as far as I know, "Kuroneko SPC" and "hoot" do.
Here are the download links for each:
* Kuroneko SPC - https://kurohane.net/seisanbutu.html
* hoot - http://dmpsoft.s17.xrea.com/

If you need a keyboard display, I recommend "Kuroneko SPC", which can use my improved SNESAPU.DLL.
Since the initial state is display in Japanese, please operate as follows:

1. Download "Kuroneko SPC" (黒猫SPC), and extract the compressed file.
2. Open "Lang" folder.
3. Copy "english.ini" file to same folder as "KuronekoSPC.exe".
4. Rename "english.ini" to "Lang.ini".

**Comment by GhbSmwc** [comment]
I've tested that (as a side note, not sure if they're open source or proprietary, given all the data isn't standalone into a single exe):
![image](https://user-images.githubusercontent.com/13095760/200427023-15f4c451-3583-4353-a58f-4473c684bfe9.png)

This is somewhat close to what bsnes plus does, only displays the currently played key on the sound viewer.

**Comment by dgrfactory** [comment]
I understand your request, but it is a far from the "simple and compact" characteristic of this player.
I think it would be a shorter way to submit requests to other products that already have the keyboard display implemented.

**Comment by dgrfactory** [comment]
https://twitter.com/nununoisy/status/1698124255018565768
https://github.com/nununoisy/spc-presenter-rs
