### ISSUE TITLE
Reading file error because of file name 

### ISSUE THREAD

**Issue by monkey03297** [dgrfactory/spcplay#59]
For exmple:
When opening a file on non-Japanese operating systems, and the file name contains Japanese characters, the program will not be able to read the file.
And if you open a file with Chinese characters on a non-Chinese system, it will show the same error.

**Comment by dgrfactory** [comment]
Hi, @monkey03297
Thank you for reporting the issue.

This problem is difficult to fix, the reasons are as follows:
* Not supported Unicode.
  * This player has been developed with an legacy language and low-level Win32 API.
  * To support Unicode, major changes are required in the code.
* Not tested on non-Japanese operating systems.
  * Originaly, this player developed for the Japanese market.
  * I have only the Japanese version of the operating system, development language, and IDE.

I will keep this issue for users who have the same request, there is no prospect of a solution.

**Comment by dgrfactory** [comment]
SPCPLAY supported Unicode from v2.20.6.
Therefore, marking this issue as fixed.
