### ISSUE TITLE
Failure to emulate echo buffer volume-related overflow effect from FIR coefficents part 2

### ISSUE THREAD

**Issue by KungFuFurby** [dgrfactory/spcplay#61]
Here I am again, forwarding more playback differences. This is the sequel to #37.

This particular song is the next test case (it uses a different set of FIR coefficients, as I had refined the distortion effect from the past two songs): https://battleofthebits.com/arena/Entry/Stop_+Duck_+Rock+and+Roll/60690/

The overflow effect appears to have been emulated incorrectly, as this song's distortion effect came out more as static noise instead of the intended distortion effect that was being done (the feedback parameter was also being fooled around in the middle of the song). To make matters worse, the static lasts throughout the entire song instead of actually stopping as intended.

[The .spc file is mirrored here in a .zip file.](https://github.com/dgrfactory/spcplay/files/12433572/BotB.60690.KungFuFurby.-.Stop.Duck.Rock.and.Roll.spc.zip)

**Comment by dgrfactory** [comment]
Hi, @KungFuFurby
Thank you for reporting the issue, and very nice sample song!

I found a mistake in the processing of the FIR filter, and fixed it in the following version.
https://github.com/dgrfactory/spcplay/releases/tag/2.19.6.8179

There seems to be a slight difference in sound yet when listening in detail.
Probably, because SNESAPU is computed in 32-bits unlike the actual device.
Still, it should have gotten a lot closer to the actual sound.
I will continue to explore ways to achieve both high quality sound and output close to the actual device.

**Comment by dgrfactory** [comment]
https://github.com/dgrfactory/spcplay/releases/tag/2.20.0.8227
